/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SearchRouteImport } from './routes/search'
import { Route as InboxThreadIdRouteImport } from './routes/inbox.$threadId'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as JobsNewRouteImport } from './routes/jobs.new'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as ProjectsNewRouteImport } from './routes/projects.new'
import { Route as SettingsBillingRouteImport } from './routes/settings.billing'
import { Route as SettingsStudioRouteImport } from './routes/settings.studio'
import { Route as StudioSlugRouteImport } from './routes/studio.$slug'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as WorksWorkIdRouteImport } from './routes/works.$workId'
import { Route as WorksNewRouteImport } from './routes/works.new'
import { Route as JobsJobIdIndexRouteImport } from './routes/jobs.$jobId.index'
import { Route as JobsJobIdEditRouteImport } from './routes/jobs.$jobId.edit'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects.$projectId.index'
import { Route as ProjectsProjectIdEditRouteImport } from './routes/projects.$projectId.edit'
import { Route as WorksWorkIdIndexRouteImport } from './routes/works.$workId.index'
import { Route as WorksWorkIdEditRouteImport } from './routes/works.$workId.edit'
import { Route as ApiPublicCardInitRouteImport } from './routes/api/public/card.init'
import { Route as ApiPublicCardVerifyRouteImport } from './routes/api/public/card.verify'
import { Route as ApiPublicPaystackInitRouteImport } from './routes/api/public/paystack.init'
import { Route as ApiPublicPaystackVerifyRouteImport } from './routes/api/public/paystack.verify'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxThreadIdRoute = InboxThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => InboxRoute,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsNewRoute = JobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsBillingRoute = SettingsBillingRouteImport.update({
  id: '/settings/billing',
  path: '/settings/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsStudioRoute = SettingsStudioRouteImport.update({
  id: '/settings/studio',
  path: '/settings/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioSlugRoute = StudioSlugRouteImport.update({
  id: '/studio/$slug',
  path: '/studio/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksWorkIdRoute = WorksWorkIdRouteImport.update({
  id: '/works/$workId',
  path: '/works/$workId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksNewRoute = WorksNewRouteImport.update({
  id: '/works/new',
  path: '/works/new',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdIndexRoute = JobsJobIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JobsJobIdRoute,
} as any)
const JobsJobIdEditRoute = JobsJobIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => JobsJobIdRoute,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdEditRoute = ProjectsProjectIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const WorksWorkIdIndexRoute = WorksWorkIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorksWorkIdRoute,
} as any)
const WorksWorkIdEditRoute = WorksWorkIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => WorksWorkIdRoute,
} as any)
const ApiPublicCardInitRoute = ApiPublicCardInitRouteImport.update({
  id: '/api/public/card/init',
  path: '/api/public/card/init',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCardVerifyRoute = ApiPublicCardVerifyRouteImport.update({
  id: '/api/public/card/verify',
  path: '/api/public/card/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaystackInitRoute = ApiPublicPaystackInitRouteImport.update({
  id: '/api/public/paystack/init',
  path: '/api/public/paystack/init',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaystackVerifyRoute = ApiPublicPaystackVerifyRouteImport.update({
  id: '/api/public/paystack/verify',
  path: '/api/public/paystack/verify',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/explore': typeof ExploreRoute
  '/favorites': typeof FavoritesRoute
  '/inbox': typeof InboxRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/inbox/$threadId': typeof InboxThreadIdRoute
  '/jobs/$jobId': typeof JobsJobIdRouteWithChildren
  '/jobs/new': typeof JobsNewRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/studio': typeof SettingsStudioRoute
  '/studio/$slug': typeof StudioSlugRoute
  '/u/$username': typeof UUsernameRoute
  '/works/$workId': typeof WorksWorkIdRouteWithChildren
  '/works/new': typeof WorksNewRoute
  '/jobs/': typeof JobsIndexRoute
  '/jobs/$jobId/edit': typeof JobsJobIdEditRoute
  '/projects/$projectId/edit': typeof ProjectsProjectIdEditRoute
  '/works/$workId/edit': typeof WorksWorkIdEditRoute
  '/jobs/$jobId/': typeof JobsJobIdIndexRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/works/$workId/': typeof WorksWorkIdIndexRoute
  '/api/public/card/init': typeof ApiPublicCardInitRoute
  '/api/public/card/verify': typeof ApiPublicCardVerifyRoute
  '/api/public/paystack/init': typeof ApiPublicPaystackInitRoute
  '/api/public/paystack/verify': typeof ApiPublicPaystackVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/explore': typeof ExploreRoute
  '/favorites': typeof FavoritesRoute
  '/inbox': typeof InboxRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/inbox/$threadId': typeof InboxThreadIdRoute
  '/jobs/new': typeof JobsNewRoute
  '/projects/new': typeof ProjectsNewRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/studio': typeof SettingsStudioRoute
  '/studio/$slug': typeof StudioSlugRoute
  '/u/$username': typeof UUsernameRoute
  '/works/new': typeof WorksNewRoute
  '/jobs': typeof JobsIndexRoute
  '/jobs/$jobId/edit': typeof JobsJobIdEditRoute
  '/projects/$projectId/edit': typeof ProjectsProjectIdEditRoute
  '/works/$workId/edit': typeof WorksWorkIdEditRoute
  '/jobs/$jobId': typeof JobsJobIdIndexRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/works/$workId': typeof WorksWorkIdIndexRoute
  '/api/public/card/init': typeof ApiPublicCardInitRoute
  '/api/public/card/verify': typeof ApiPublicCardVerifyRoute
  '/api/public/paystack/init': typeof ApiPublicPaystackInitRoute
  '/api/public/paystack/verify': typeof ApiPublicPaystackVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/explore': typeof ExploreRoute
  '/favorites': typeof FavoritesRoute
  '/inbox': typeof InboxRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/inbox/$threadId': typeof InboxThreadIdRoute
  '/jobs/$jobId': typeof JobsJobIdRouteWithChildren
  '/jobs/new': typeof JobsNewRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/studio': typeof SettingsStudioRoute
  '/studio/$slug': typeof StudioSlugRoute
  '/u/$username': typeof UUsernameRoute
  '/works/$workId': typeof WorksWorkIdRouteWithChildren
  '/works/new': typeof WorksNewRoute
  '/jobs/': typeof JobsIndexRoute
  '/jobs/$jobId/edit': typeof JobsJobIdEditRoute
  '/projects/$projectId/edit': typeof ProjectsProjectIdEditRoute
  '/works/$workId/edit': typeof WorksWorkIdEditRoute
  '/jobs/$jobId/': typeof JobsJobIdIndexRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/works/$workId/': typeof WorksWorkIdIndexRoute
  '/api/public/card/init': typeof ApiPublicCardInitRoute
  '/api/public/card/verify': typeof ApiPublicCardVerifyRoute
  '/api/public/paystack/init': typeof ApiPublicPaystackInitRoute
  '/api/public/paystack/verify': typeof ApiPublicPaystackVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/explore'
    | '/favorites'
    | '/inbox'
    | '/notifications'
    | '/pricing'
    | '/profile'
    | '/search'
    | '/inbox/$threadId'
    | '/jobs/$jobId'
    | '/jobs/new'
    | '/projects/$projectId'
    | '/projects/new'
    | '/settings/billing'
    | '/settings/studio'
    | '/studio/$slug'
    | '/u/$username'
    | '/works/$workId'
    | '/works/new'
    | '/jobs/'
    | '/jobs/$jobId/edit'
    | '/projects/$projectId/edit'
    | '/works/$workId/edit'
    | '/jobs/$jobId/'
    | '/projects/$projectId/'
    | '/works/$workId/'
    | '/api/public/card/init'
    | '/api/public/card/verify'
    | '/api/public/paystack/init'
    | '/api/public/paystack/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/explore'
    | '/favorites'
    | '/inbox'
    | '/notifications'
    | '/pricing'
    | '/profile'
    | '/search'
    | '/inbox/$threadId'
    | '/jobs/new'
    | '/projects/new'
    | '/settings/billing'
    | '/settings/studio'
    | '/studio/$slug'
    | '/u/$username'
    | '/works/new'
    | '/jobs'
    | '/jobs/$jobId/edit'
    | '/projects/$projectId/edit'
    | '/works/$workId/edit'
    | '/jobs/$jobId'
    | '/projects/$projectId'
    | '/works/$workId'
    | '/api/public/card/init'
    | '/api/public/card/verify'
    | '/api/public/paystack/init'
    | '/api/public/paystack/verify'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/explore'
    | '/favorites'
    | '/inbox'
    | '/notifications'
    | '/pricing'
    | '/profile'
    | '/search'
    | '/inbox/$threadId'
    | '/jobs/$jobId'
    | '/jobs/new'
    | '/projects/$projectId'
    | '/projects/new'
    | '/settings/billing'
    | '/settings/studio'
    | '/studio/$slug'
    | '/u/$username'
    | '/works/$workId'
    | '/works/new'
    | '/jobs/'
    | '/jobs/$jobId/edit'
    | '/projects/$projectId/edit'
    | '/works/$workId/edit'
    | '/jobs/$jobId/'
    | '/projects/$projectId/'
    | '/works/$workId/'
    | '/api/public/card/init'
    | '/api/public/card/verify'
    | '/api/public/paystack/init'
    | '/api/public/paystack/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  ExploreRoute: typeof ExploreRoute
  FavoritesRoute: typeof FavoritesRoute
  InboxRoute: typeof InboxRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  JobsJobIdRoute: typeof JobsJobIdRouteWithChildren
  JobsNewRoute: typeof JobsNewRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  ProjectsNewRoute: typeof ProjectsNewRoute
  SettingsBillingRoute: typeof SettingsBillingRoute
  SettingsStudioRoute: typeof SettingsStudioRoute
  StudioSlugRoute: typeof StudioSlugRoute
  UUsernameRoute: typeof UUsernameRoute
  WorksWorkIdRoute: typeof WorksWorkIdRouteWithChildren
  WorksNewRoute: typeof WorksNewRoute
  JobsIndexRoute: typeof JobsIndexRoute
  ApiPublicCardInitRoute: typeof ApiPublicCardInitRoute
  ApiPublicCardVerifyRoute: typeof ApiPublicCardVerifyRoute
  ApiPublicPaystackInitRoute: typeof ApiPublicPaystackInitRoute
  ApiPublicPaystackVerifyRoute: typeof ApiPublicPaystackVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/$threadId': {
      id: '/inbox/$threadId'
      path: '/$threadId'
      fullPath: '/inbox/$threadId'
      preLoaderRoute: typeof InboxThreadIdRouteImport
      parentRoute: typeof InboxRoute
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/new': {
      id: '/jobs/new'
      path: '/jobs/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof JobsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/billing': {
      id: '/settings/billing'
      path: '/settings/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof SettingsBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/studio': {
      id: '/settings/studio'
      path: '/settings/studio'
      fullPath: '/settings/studio'
      preLoaderRoute: typeof SettingsStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/$slug': {
      id: '/studio/$slug'
      path: '/studio/$slug'
      fullPath: '/studio/$slug'
      preLoaderRoute: typeof StudioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works/$workId': {
      id: '/works/$workId'
      path: '/works/$workId'
      fullPath: '/works/$workId'
      preLoaderRoute: typeof WorksWorkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works/new': {
      id: '/works/new'
      path: '/works/new'
      fullPath: '/works/new'
      preLoaderRoute: typeof WorksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId/': {
      id: '/jobs/$jobId/'
      path: '/'
      fullPath: '/jobs/$jobId/'
      preLoaderRoute: typeof JobsJobIdIndexRouteImport
      parentRoute: typeof JobsJobIdRoute
    }
    '/jobs/$jobId/edit': {
      id: '/jobs/$jobId/edit'
      path: '/edit'
      fullPath: '/jobs/$jobId/edit'
      preLoaderRoute: typeof JobsJobIdEditRouteImport
      parentRoute: typeof JobsJobIdRoute
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/edit': {
      id: '/projects/$projectId/edit'
      path: '/edit'
      fullPath: '/projects/$projectId/edit'
      preLoaderRoute: typeof ProjectsProjectIdEditRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/works/$workId/': {
      id: '/works/$workId/'
      path: '/'
      fullPath: '/works/$workId/'
      preLoaderRoute: typeof WorksWorkIdIndexRouteImport
      parentRoute: typeof WorksWorkIdRoute
    }
    '/works/$workId/edit': {
      id: '/works/$workId/edit'
      path: '/edit'
      fullPath: '/works/$workId/edit'
      preLoaderRoute: typeof WorksWorkIdEditRouteImport
      parentRoute: typeof WorksWorkIdRoute
    }
    '/api/public/card/init': {
      id: '/api/public/card/init'
      path: '/api/public/card/init'
      fullPath: '/api/public/card/init'
      preLoaderRoute: typeof ApiPublicCardInitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/card/verify': {
      id: '/api/public/card/verify'
      path: '/api/public/card/verify'
      fullPath: '/api/public/card/verify'
      preLoaderRoute: typeof ApiPublicCardVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paystack/init': {
      id: '/api/public/paystack/init'
      path: '/api/public/paystack/init'
      fullPath: '/api/public/paystack/init'
      preLoaderRoute: typeof ApiPublicPaystackInitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paystack/verify': {
      id: '/api/public/paystack/verify'
      path: '/api/public/paystack/verify'
      fullPath: '/api/public/paystack/verify'
      preLoaderRoute: typeof ApiPublicPaystackVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface InboxRouteChildren {
  InboxThreadIdRoute: typeof InboxThreadIdRoute
}

const InboxRouteChildren: InboxRouteChildren = {
  InboxThreadIdRoute: InboxThreadIdRoute,
}

const InboxRouteWithChildren = InboxRoute._addFileChildren(InboxRouteChildren)

interface JobsJobIdRouteChildren {
  JobsJobIdEditRoute: typeof JobsJobIdEditRoute
  JobsJobIdIndexRoute: typeof JobsJobIdIndexRoute
}

const JobsJobIdRouteChildren: JobsJobIdRouteChildren = {
  JobsJobIdEditRoute: JobsJobIdEditRoute,
  JobsJobIdIndexRoute: JobsJobIdIndexRoute,
}

const JobsJobIdRouteWithChildren = JobsJobIdRoute._addFileChildren(
  JobsJobIdRouteChildren,
)

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdEditRoute: typeof ProjectsProjectIdEditRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdEditRoute: ProjectsProjectIdEditRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

interface WorksWorkIdRouteChildren {
  WorksWorkIdEditRoute: typeof WorksWorkIdEditRoute
  WorksWorkIdIndexRoute: typeof WorksWorkIdIndexRoute
}

const WorksWorkIdRouteChildren: WorksWorkIdRouteChildren = {
  WorksWorkIdEditRoute: WorksWorkIdEditRoute,
  WorksWorkIdIndexRoute: WorksWorkIdIndexRoute,
}

const WorksWorkIdRouteWithChildren = WorksWorkIdRoute._addFileChildren(
  WorksWorkIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  ExploreRoute: ExploreRoute,
  FavoritesRoute: FavoritesRoute,
  InboxRoute: InboxRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  JobsJobIdRoute: JobsJobIdRouteWithChildren,
  JobsNewRoute: JobsNewRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  ProjectsNewRoute: ProjectsNewRoute,
  SettingsBillingRoute: SettingsBillingRoute,
  SettingsStudioRoute: SettingsStudioRoute,
  StudioSlugRoute: StudioSlugRoute,
  UUsernameRoute: UUsernameRoute,
  WorksWorkIdRoute: WorksWorkIdRouteWithChildren,
  WorksNewRoute: WorksNewRoute,
  JobsIndexRoute: JobsIndexRoute,
  ApiPublicCardInitRoute: ApiPublicCardInitRoute,
  ApiPublicCardVerifyRoute: ApiPublicCardVerifyRoute,
  ApiPublicPaystackInitRoute: ApiPublicPaystackInitRoute,
  ApiPublicPaystackVerifyRoute: ApiPublicPaystackVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
